import { Pokemon } from "./pokemon";

export const POKEMONS: Pokemon[] = [
  {
    id: 1,
    name: "Bulbizarre",
    hp: 25,
    cp: 5,
    types: ["grass", "poison"],
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/001.png",
    created: new Date(),
  },
  {
    id: 2,
    name: "Ivysaur",
    hp: 28,
    cp: 6,
    types: ["grass", "poison"],
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/002.png",
    created: new Date(),
  },
  {
    id: 3,
    name: "Venusaur",
    hp: 21,
    cp: 4,
    types: ["grass", "poison"],
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/003.png",
    created: new Date(),
  },
  {
    id: 4,
    types: ["fire"],
    hp: 16,
    cp: 2,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/004.png",
    name: "Charmander",
    created: new Date(),
  },
  {
    id: 5,
    types: ["fire"],
    hp: 30,
    cp: 7,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/005.png",
    name: "Charmeleon",
    created: new Date(),
  },
  {
    id: 6,
    types: ["Normal", "Vol"],
    hp: 18,
    cp: 6,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/006.png",
    name: "Rattata",
    created: new Date(),
  },
  {
    id: 7,
    types: ["Normal", "Vol"],
    hp: 14,
    cp: 5,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/007.png",
    name: "Piafabec",
    created: new Date(),
  },
  {
    id: 8,
    types: ["Poison"],
    hp: 16,
    cp: 4,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/008.png",
    name: "Abo",
    created: new Date(),
  },
  {
    id: 9,
    types: ["Electrik"],
    hp: 21,
    cp: 7,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/009.png",
    name: "Pikachu",
    created: new Date(),
  },
  {
    id: 10,
    types: ["Normal"],
    hp: 19,
    cp: 3,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/010.png",
    name: "Sabalette",
    created: new Date(),
  },
  {
    id: 11,
    types: ["Fée"],
    hp: 25,
    cp: 5,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/011.png",
    name: "Mélofée",
    created: new Date(),
  },
  {
    id: 12,
    types: ["Feu"],
    hp: 17,
    cp: 8,
    picture: "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/012.png",
    name: "Groupix",
    created: new Date(),
  },
];
